BPS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('reservation/', include('reservation.urls')),
    path('contact/', include('contact.urls')),
    path('hosts/', include('administration.urls')),
]

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contacts, name='contacts'),
    path('send_message/', views.send_message, name='send_message'),

]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.sign_up, name='signup'),
    path('logging_in/', views.logging_in, name='logging_in'),
    path('logging_out/', views.logging_out, name='logging_out'),
    path('signing_up/', views.signing_up, name='signing_up'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('about/', views.about, name='about'),
]

login/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_picture = models.ImageField(upload_to='login/static/login/storage', blank=True, null=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=13)
    birthday = models.DateField()
    gender = models.CharField(max_length=6)


class User_File(models.Model):
    user = models.OneToOneField(Profile, on_delete=models.DO_NOTHING)
    file = models.FileField(upload_to='login/static/login/storage', blank=True, null=True)

login/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Profile
from django.contrib.auth.models import User
from django.urls import reverse
# Create your views here.


def index(request):
    context = {

    }
    return render(request, 'login/homepage.html', context)


def sign_up(request):
    context = {

    }
    return render(request, 'signup/signup.html', context)


def signing_up(request):
    ready = False
    username = request.POST.get('username')
    password = request.POST.get('password')
    email = request.POST.get('email')
    user = User.objects.create_user(username, email, password)
    first_name = request.POST.get('user_first_name')
    last_name = request.POST.get('user_last_name')
    phone_number = request.POST.get('user_number')
    birthday = request.POST.get('user_birthday')
    user_gender = request.POST.get('user_gender')
    profile = Profile(
            user=user,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            birthday=birthday,
            gender=user_gender)
    ready = True

    if ready:
        profile.save()
        return HttpResponseRedirect(reverse('login:index'))
    else:
        return HttpResponseRedirect(reverse('login:signup'))


def logging_in(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    auth = User.objects.get(username=username)
    user = authenticate(request, username=username, password=password)
    request.session['user'] = username
    if user is not None:
        login(request, user)
        if auth.is_superuser:
            return HttpResponseRedirect(reverse('administration:index'))
        else:
            return HttpResponseRedirect(reverse('login:dashboard'))
    else:
        return render(request, 'login/homepage.html', {})


def logging_out(request):
    del request.session['user']
    logout(request)
    return HttpResponseRedirect(reverse('login:index'))


def dashboard(request):
    username = request.session['user']
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    context = {
        'users': profile
    }
    return render(request, 'dashboard/dashboard.html', context)


def about(request):
    return render(request, 'about/about.html', {})

login/templates/login/homepage.html
<!DOCTYPE html>
<html>
<head>

<title>Project</title>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'login/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'login/css/style1.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'login/css/style2.css' %}">

<style>
body  {
    background-image: url("{% static 'login/image/picture.jpg' %}");
	margin: 0;
	padding: 0;
    background-size: cover;
	background-size: center;
}
</style>
<header>
 <div class="main">
 <ul>
  <li class="active"><a href={% url 'login:index' %}>Home</a></li>
     <li><a href="{% url 'login:about' %}">About</a></li>
  <li type="button"><a href="{% url 'contact:contacts' %}">Contact</a></li>
  <li type="button"/><a href="{% url 'login:signup' %}">Sign Up</a></li>
  
  </ul>
  </div>
  </div>
  </header>

<body>
<div class="home">
<div class="slideshow-container">

<div class="mySlides fade">
  <div class="numbertext">1 / 3</div>
  <img src="{% static 'login/image/images.jpg' %}" style="width:900px; height:500px;">
  <div class="text">Caption Text</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">2 / 3</div>
  <img src="{% static 'login/image/images2.jpg' %}" style="width:900px; height:500px;">
  <div class="text">Caption Two</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">3 / 3</div>
  <img src="{% static 'login/image/images3.jpg' %}" style="width:900px; height:500px" ;>
  <div class="text">Caption Three</div>
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span> 
  <span class="dot"></span> 
  <span class="dot"></span> 
</div>





<div class="loginbox">
<img src="{% static 'login/image/user1.png' %}" class="user">
   <h1>Log In</h1>
   <form method="post" action="{% url 'login:logging_in' %}">
       {% csrf_token %}
      <p>Username</p>
	  <input type="text" name="username" required >
	  <p>Password</p>
	  <input type="password" name="password" required >
      <input type="submit" value="Login">
	  </p>
   </form>

</div>

  </body>
  <script>
var slideIndex = 0;
showSlides();

function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    for (i = 0; i < slides.length; i++) {
       slides[i].style.display = "none";  
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}    
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";  
    dots[slideIndex-1].className += " active";
    setTimeout(showSlides, 2000); // Change image every 2 seconds
}
</script>

  </head>
  </html>