BPS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('reservation/', include('reservation.urls')),
    path('contact/', include('contact.urls')),
    path('hosts/', include('administration.urls')),
]

administration/urls.py
from django.urls import path

from . import views

app_name = 'administration'

urlpatterns = [
    path('', views.index, name='index'),
    path('calendar/', views.calendar, name='calendar'),
    path('add_event/', views.adding_event, name='add_event'),
    path('del_event/', views.deleting_event, name='del_event'),
    path('get_events/', views.get_events, name='get_events'),
    path('user_info/', views.user_info, name='user_info'),
    path('payment_info/', views.payments_info, name='payments_info'),
    path('editing_user/<int:user_id>', views.editing_user, name='editing_user'),
    path('edit/<int:user_id>', views.edit, name='edit'),
    path('deleting_user/<int:user_id>', views.deleting_user, name='deleting_user'),
    path('message/', views.message, name='message'),
    path('deleting_message/<int:message_id>', views.deleting_message, name='deleting_message'),
]

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contacts, name='contacts'),
    path('send_message/', views.send_message, name='send_message'),

]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.sign_up, name='signup'),
    path('logging_in/', views.logging_in, name='logging_in'),
    path('logging_out/', views.logging_out, name='logging_out'),
    path('signing_up/', views.signing_up, name='signing_up'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('about/', views.about, name='about'),
]

administration/models.py
from django.db import models

# Create your models here.
from login.models import Profile


class Payments(models.Model):
    patient = models.ForeignKey(Profile, on_delete=models.DO_NOTHING)
    date = models.DateField()
    amount = models.IntegerField()

administration/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render


# Create your views here.
from django.urls import reverse

from administration.models import Payments
from contact.models import Message
from login.models import Profile
from reservation.models import Event


def index(request):
    context = {

    }
    return render(request, 'administration/main.html', context)


def calendar(request):
    context ={

    }
    return render(request, 'administration/events.html', context)


def get_events(request):
    data_list = []
    events = Event.objects.all()
    for each in events:
        temp = {
            'title': each.title,
            'start': each.start,
            'end': each.end,
        }
        data_list.append(temp)
    return JsonResponse(data_list, safe=False)

def adding_event(request):
    title = request.GET.get('title', None)
    start = request.GET.get('start', None)
    end = request.GET.get('end', None)
    event = Event(
        title=str(title),
        start=str(start),
        end=str(end)
    )
    event.save()
    data = {
        "title": title,
        "start": start,
        "end": end
             }
    return JsonResponse(data)


def deleting_event(request):
    title = request.GET.get('title', None)
    start = request.GET.get('start', None)
    end = request.GET.get('end', None)
    event = Event.objects.get(title=title)
    event.delete()
    data = {
        "title": title,
        "start": start,
        "end": end
             }
    return JsonResponse(data)


def user_info(request):
    profile = Profile.objects.all()
    context = {
        'profiles': profile,
    }
    return render(request, 'administration/user.html', context)


def payments_info(request):
    payments = Payments.objects.all()
    context = {
        'payments': payments
    }
    return render(request, 'administration/payments.html', context)


def edit(request, user_id):
    user = Profile.objects.get(pk=user_id)
    context = {
        'users': user
    }
    return render(request, 'administration/edit.html', context)


def editing_user(request, user_id):
    user_new = Profile.objects.get(pk=user_id)
    user_new.first_name = request.POST.get('user_first_name')
    user_new.last_name = request.POST.get('user_last_name')
    user_new.phone_number = request.POST.get('user_number')
    user_new.birthday = request.POST.get('user_birthday')
    user_new.save()
    return HttpResponseRedirect(reverse('administration:index'))


def deleting_user(request, user_id):
    user = Profile.objects.get(pk=user_id)
    user.delete()
    return HttpResponseRedirect(reverse('administration:user_info'))


def message(request):
    messages = Message.objects.all()
    context = {
        'messages': messages
    }
    return render(request, 'administration/message.html', context)


def deleting_message(request, message_id):
    messages = Message.objects.get(pk=message_id)
    messages.delete()
    return HttpResponseRedirect(reverse('administration:message'))

administration/templates/administration/admin.html
<!DOCTYPE html>
<html lang="en">
<header>
    <title>BPS</title>
        {% load static %}
     <link rel="stylesheet" type="text/css" href="{% static 'administration/css/style.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'administration/css/style1.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'administration/css/style2.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'administration/css/style3.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'administration/css/style4.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'administration/css/fullcalendar.css' %}">
     <script src="{% static 'administration/js/jquery.min.js' %}"></script>
     <script src="{% static 'administration/js/moment.min.js' %}"></script>
     <script src="{% static 'administration/js/fullcalendar.js' %}"></script>
     <script src="{% static 'administration/js/script.js' %}"></script>
       <style>
        body {
            background-image: url("{% static 'calendar/image/picture.jpg' %}");
            margin: 0;
            padding: 0;
            background-size: cover;
            background-size: center;
        }
    </style>
    <style>
 body {
  margin-top: 40px;
  text-align: center;
  font-size: 14px;
  font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
  }
 #calendar {
  width: 900px;
  height: 473px;
  margin: 0 auto;
     background-color: #1CB0B4;
  }
 .container{
     width: 1000px;
     height: 582px;
     background-color: #098588;
 }
</style>
</header>
<body>
	<div class="container">
		<div class="row">
			<div id="calendar"></div>

		</div>
	</div>
</body>
</html>

administration/templates/administration/edit.html
<!DOCTYPE html>
<html>
<head>


<title>Project</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'login/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'login/css/style1.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'login/css/style2.css' %}">
<style>

body  {
    background-image: url("{% static 'login/image/picture.jpg' %}");
	margin: 0;
	padding: 0;
    background-size: 100%;
	background-attachment: fixed;
}
</style>
<header>

 <div class="main">
 <ul>
  <li type="button"><a href="{% url 'login:index' %}">Home</a></li>
  <li><a href="#">About</a></li>
  <li type="button"><a href="{% url 'contact:contacts' %}">Contact</a></li>
  <li class="active"><a href="#">Sign Up</a></li>

  </ul>
  </div>
  </header>
<body>
<div class="registrationbox">
   <form method="post" action="{% url 'administration:editing_user' user_id=users.id %}">
       {% csrf_token %}
	<div class = "regbox">
	<img src="{% static 'login/image/reg1.png' %}" class="reg">
	<h1>Edit an Account</h1>
	<div class = "upper">
		<div class = "upperleft">
	  <input  type="text"  name="user_first_name" value="{{ users.first_name }}" pattern="[A-Z/a-z]+" required >
		</div>
		<div class = "upperright">
	  <input type="text" name="user_last_name" value="{{ users.last_name }}" pattern="[A-Z/a-z]+" required >
		</div>
	  <div class = "lowermid">
	   <h1>Phone Number</h1>
	  <input type="text" name="user_number" value="{{ users.phone_number }}" pattern="[0-9]{11}" required >
	  </div>
	  <div class = "lower">
	  <center><h1>Birthday</h1></center>
          <input name="user_birthday" type="date" value="{{ users.birthday|date:"Y-m-d" }}">
		</div>
		<div class = "pass">

	</div>
	<div class = "lowbox"><center>
		<div class = "lowupinside">
	  <input type="submit" name="submit" value="Submit">
		</div>
		<div class = "lowdowninside">
	  <input type="submit" name="" value="Cancel">
	  </div>
	 </div></center>
	  </div>
	  </div>

	  </div>
	  </form>
</div>



  </body>
  </head>
  </html>

administration/templates/administration/events.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'administration/css/fullcalendar.css' %}">
    <script src="{% static 'administration/js/jquery.min.js' %}"></script>
    <script src="{% static 'administration/js/moment.min.js' %}"></script>
    <script src="{% static 'administration/js/fullcalendar.js' %}"></script>
    <script src="{% static 'administration/js/script.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'administration/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'administration/css/user.css' %}">


</head>
<body>

<div class="header">
    <a href="#" class="nav-trigger"><span></span></a>
</div>

<div class="side-nav">
    <nav>
        <ul>
            <li>
                <a href="{% url 'administration:user_info' %}">
                    <span><i class="fa fa-user"></i></span>
                    <span>&nbspUsers</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:message' %}">
                    <span><i class="fa fa-envelope"></i></span>
                    <span>&nbspMessages</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:calendar' %}">
                    <span><i class="fa fa-calendar"></i></span>
                    <span>&nbspEvents</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:payments_info' %}">
                    <span><i class="fa fa-credit-card-alt"></i></span>
                    <span>&nbspPayments</span>
                </a>
            </li>
            <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            <div class="signout">
                <li>
                    <a href="{% url 'login:logging_out' %}">
                        <span><i class="fa fa-sign-out"></i></span>

                        <span>&nbspSign Out</span>

                    </a>
            </div>
            </li>

        </ul>
    </nav>
</div>
<div class="userbox">
    <center>
        <h1>Reservations</h1>
    </center>
    <div class="class-container">
    <div class="row">
        <div id="calendar"></div>

    </div>
</div>

</div>


</body>
</html>

administration/templates/administration/main.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'administration/css/main.css' %}">



</head>
<body>

<div class="header">
    <a href="#" class="nav-trigger"><span></span></a>
</div>

<div class="side-nav">
    <nav>
        <ul>
            <li>
                <a href="{% url 'administration:user_info' %}">
                    <span><i class="fa fa-user"></i></span>
                    <span>&nbspUsers</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:message' %}">
                    <span><i class="fa fa-envelope"></i></span>
                    <span>&nbspMessages</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:calendar' %}">
                    <span><i class="fa fa-calendar"></i></span>
                    <span>&nbspEvents</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:payments_info' %}">
                    <span><i class="fa fa-credit-card-alt"></i></span>
                    <span>&nbspPayments</span>
                </a>
            </li>

        </ul>
    </nav>
</div>

<div class="maincontent">
</div>

</body>
</html>

administration/templates/administration/message.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'administration/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'administration/css/user.css' %}">


</head>
<body>

<div class="header">
    <a href="#" class="nav-trigger"><span></span></a>
</div>

<div class="side-nav">
    <nav>
        <ul>
            <li>
                <a href="{% url 'administration:user_info' %}">
                    <span><i class="fa fa-user"></i></span>
                    <span>&nbspUsers</span>
                </a>
            </li>

            <li><a href="{% url 'administration:message' %}">
                    <span><i class="fa fa-envelope"></i></span>
                    <span>&nbspMessages</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:calendar' %}">
                    <span><i class="fa fa-calendar"></i></span>
                    <span>&nbspEvents</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:payments_info' %}">
                    <span><i class="fa fa-credit-card-alt"></i></span>
                    <span>&nbspPayments</span>
                </a>
            </li>
            <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            <div class="signout">
                <li>
                    <a href="{% url 'login:logging_out' %}">
                        <span><i class="fa fa-sign-out"></i></span>

                        <span>&nbspSign Out</span>

                    </a>
                </li>
            </div>


        </ul>
    </nav>
</div>
<div class="userbox">
    <h1>Messages</h1>
    <table>

        <tr>
            <th>Sender's Name</th>
            <th>Email</th>
            <th>Message</th>
            <th>Action</th>
        </tr>
        {% for message in messages %}
        <tr>
            <td>{{ message.name }}</td>
            <td>{{ message.email }}</td>
            <td>{{ message.message }}</td>
            <td>

                <p>
                    <a href="{% url 'administration:deleting_message' message_id=message.id %}" class="btn btn-danger pull-right1" data-placement="top" data-toggle="tooltip" title="Delete">
                        <span class="fa fa-trash"> </span>
                    </a>
                </p>
            </td>
        </tr>
        {% endfor %}


</div>


</body>
</html>

administration/templates/administration/payments.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'administration/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'administration/css/user.css' %}">



</head>
<body>

<div class="header">
    <a href="#" class="nav-trigger"><span></span></a>
</div>

<div class="side-nav">
    <nav>
        <ul>
            <li>
                <a href="{% url 'administration:user_info' %}">
                    <span><i class="fa fa-user"></i></span>
                    <span>&nbspUsers</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:message' %}">
                    <span><i class="fa fa-envelope"></i></span>
                    <span>&nbspMessages</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:calendar' %}">
                    <span><i class="fa fa-calendar"></i></span>
                    <span>&nbspEvents</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:payments_info' %}">
                    <span><i class="fa fa-credit-card-alt"></i></span>
                    <span>&nbspPayments</span>
                </a>
            </li>
            <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            <div class="signout">
                <li>
                    <a href="{% url 'login:logging_out' %}">
                        <span><i class="fa fa-sign-out"></i></span>

                        <span>&nbspSign Out</span>

                    </a>
            </div>
            </li>

        </ul>
    </nav>
</div>
<div class="userbox">
    <h1>Transaction History</h1>
    <table>

        <tr>
            <th>First name</th>
            <th>Last Name</th>
            <th>Date</th>
            <th>Phone Number</th>
            <th>Method</th>
            <th>Amount</th>
            <th>Action</th>
        </tr>
        {% for payment in payments %}
        <tr>
            <td>{{ payment.patient.first_name }}</td>
            <td>{{ payment.patient.last_name }}</td>
            <td>{{ payment.date }}</td>
            <td>{{ payment.patient.phone_number }}</td>
            <td>PayPal</td>
            <td>{{ payment.amount }}</td>
            <td>
                <p>
                    <button class="btn btn-primary pull-right1" data-placement="top" data-toggle="tooltip" title="Edit">
                        <span class="fa fa-edit"></span>
                    </button>

                    <button class="btn btn-danger pull-right1" data-placement="top" data-toggle="tooltip" title="Delete">
                        <span class="fa fa-trash"> </span>
                    </button>
                </p>
            </td>
        </tr>
        {% endfor %}

</div>


</body>
</html>

administration/templates/administration/user.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'administration/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'administration/css/user.css' %}">


    <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>


</head>
<body>

<div class="header">
    <a href="#" class="nav-trigger"><span></span></a>
</div>

<div class="side-nav">
    <nav>
        <ul>
            <li>
                <a href="{% url 'administration:user_info' %}">
                    <span><i class="fa fa-user"></i></span>
                    <span>&nbspUsers</span>
                </a>
            </li>

            <li>
                <a href="#">
                    <span><i class="fa fa-envelope"></i></span>
                    <span>&nbspMessages</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:calendar' %}">
                    <span><i class="fa fa-calendar"></i></span>
                    <span>&nbspEvents</span>
                </a>
            </li>

            <li>
                <a href="{% url 'administration:payments_info' %}">
                    <span><i class="fa fa-credit-card-alt"></i></span>
                    <span>&nbspPayments</span>
                </a>
            </li>
            <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            <div class="signout">
                <li>
                    <a href="{% url 'login:index' %}">
                        <span><i class="fa fa-sign-out"></i></span>

                        <span>&nbspSign Out</span>

                    </a>
            </div>
            </li>

        </ul>
    </nav>
</div>
<div class="userbox">
    <h1>Patient's Info</h1>
    <table>

        <tr>
            <th>First name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Birthday</th>
            <th>Gender</th>
            <th>Action</th>
        </tr>
        {% for profile in profiles %}
        <tr>
            <td>{{ profile.first_name }}</td>
            <td>{{ profile.last_name }}</td>
            <td>{{ profile.user.email }}</td>
            <td>{{ profile.phone_number }}</td>
            <td>{{ profile.birthday }}</td>
            <td>{{ profile.gender }}</td>
            <td>

                <p>
                    <form action=" {% url 'administration:edit' user_id=profile.id %} "
                                      method="post">
                                    {% csrf_token %}
                    <button class="btn btn-primary pull-right1" data-placement="top" data-toggle="tooltip" title="Edit">
                        <span class="fa fa-edit"></span>
                    </button>
                    </form>

                    <a href="{% url 'administration:deleting_user' user_id=profile.id %}" class="btn btn-danger pull-right1" data-placement="top" data-toggle="tooltip" title="Delete">
                        <span class="fa fa-trash"> </span>
                    </a>
                </p>
            </td>
        </tr>
        {% endfor %}


</div>


</body>
</html>