BPS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('reservation/', include('reservation.urls')),
    path('contact/', include('contact.urls')),
    path('hosts/', include('administration.urls')),
]

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contacts, name='contacts'),
    path('send_message/', views.send_message, name='send_message'),

]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.sign_up, name='signup'),
    path('logging_in/', views.logging_in, name='logging_in'),
    path('logging_out/', views.logging_out, name='logging_out'),
    path('signing_up/', views.signing_up, name='signing_up'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('about/', views.about, name='about'),
]

reservation/urls.py
from django.urls import path

from . import views

app_name = 'reservation'

urlpatterns = [
    path('calendar/', views.calendar, name='calendar'),
    path('add_event/', views.adding_event, name='add_event'),
    path('del_event/', views.deleting_event, name='del_event'),
    path('get_events/', views.get_events, name='get_events'),
    path('payment/', views.payment, name='payment'),
]

login/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_picture = models.ImageField(upload_to='login/static/login/storage', blank=True, null=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=13)
    birthday = models.DateField()
    gender = models.CharField(max_length=6)


class User_File(models.Model):
    user = models.OneToOneField(Profile, on_delete=models.DO_NOTHING)
    file = models.FileField(upload_to='login/static/login/storage', blank=True, null=True)

login/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Profile
from django.contrib.auth.models import User
from django.urls import reverse
# Create your views here.


def index(request):
    context = {

    }
    return render(request, 'login/homepage.html', context)


def sign_up(request):
    context = {

    }
    return render(request, 'signup/signup.html', context)


def signing_up(request):
    ready = False
    username = request.POST.get('username')
    password = request.POST.get('password')
    email = request.POST.get('email')
    user = User.objects.create_user(username, email, password)
    first_name = request.POST.get('user_first_name')
    last_name = request.POST.get('user_last_name')
    phone_number = request.POST.get('user_number')
    birthday = request.POST.get('user_birthday')
    user_gender = request.POST.get('user_gender')
    profile = Profile(
            user=user,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            birthday=birthday,
            gender=user_gender)
    ready = True

    if ready:
        profile.save()
        return HttpResponseRedirect(reverse('login:index'))
    else:
        return HttpResponseRedirect(reverse('login:signup'))


def logging_in(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    auth = User.objects.get(username=username)
    user = authenticate(request, username=username, password=password)
    request.session['user'] = username
    if user is not None:
        login(request, user)
        if auth.is_superuser:
            return HttpResponseRedirect(reverse('administration:index'))
        else:
            return HttpResponseRedirect(reverse('login:dashboard'))
    else:
        return render(request, 'login/homepage.html', {})


def logging_out(request):
    del request.session['user']
    logout(request)
    return HttpResponseRedirect(reverse('login:index'))


def dashboard(request):
    username = request.session['user']
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    context = {
        'users': profile
    }
    return render(request, 'dashboard/dashboard.html', context)


def about(request):
    return render(request, 'about/about.html', {})

login/templates/dashboard/dashboard.html
<!DOCTYPE html>
<html>
<head>


<title>Project</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'login/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'login/css/style1.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'login/css/style2.css' %}">
<style>

body  {
    background-image: url("{% static 'login/image/picture.jpg' %}");
	margin: 0;
	padding: 0;
    background-size: 100%;
	background-attachment: fixed;
}
</style>
<header>

 <div class="main">
 <ul>
  <li type="button"><a href="{% url 'login:index' %}">Home</a></li>
  <li><a href="{% url 'login:about' %}">About</a></li>
  <li type="button"><a href="{% url 'contact:contacts' %}">Contact</a></li>
  <li class="active"><a href="{% url 'login:signup' %}">Sign Up</a></li>

  </ul>
  </div>
  </header>
<body>
<div class="registrationbox">
   <form method="post" action="{% url 'reservation:calendar' %}">
       {% csrf_token %}
	<div class = "regbox">
	<img src="{% static 'login/image/reg1.png' %}" class="reg">
	<h1>Your Profile</h1>
	<div class = "upper">
        <div class = "upperperleft">
            <label>{{ users.user.username }}</label>
		</div>
		<div class = "upperleft">
            <label>{{ users.first_name }}</label>
		</div>
		<div class = "upperright">
            <label>{{ users.last_name }}</label>
		</div>
		<div class = "midmid">
            <label>{{ users.user.email }}</label>
	  </div>
	  <div class = "lowermid">
	   <h1>Phone Number</h1>
          <label>{{ users.phone_number }}</label>
	  </div>
	  <div class = "lower">
	  <center><h1>Birthday</h1></center>
          <label>{{ users.birthday }}</label>
		</div>

		<div class = "pass">

	</div>
	<div class = "lowbox"><center>
		<div class = "lowupinside">
	  <input type="submit" name="submit" value="Make a Reservation">
            <a href="{% url 'login:logging_out' %}" >
            <span><i class="fa fa-sign-out"></i></span>

                        <span>&nbspSign Out</span>
                </a>
		</div>
	 </div></center>
	  </div>
	  </div>

	  </div>
	  </form>
</div>



  </body>
  </head>
  </html>